# Generated by Django 3.2.20 on 2023-08-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230813_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sum',
            new_name='suma',
        ),
    ]
